### ISSUE TITLE
SyntaxError: JSON position 26

### ISSUE THREAD

**Issue by Phaired** [PrismarineJS/mineflayer#1120]
```var mineflayer = require('mineflayer');
var AutoAuth = require('mineflayer-auto-auth');
var bot = mineflayer.createBot({

  host: 'play.hadaria.fr',
  port: 25565,
  username: "poelerles", 
  version: false,
  plugins: [AutoAuth],
  AutoAuth: 'password'
});
bot.on('error', err => console.log(err))```
this make the error : 
```root@vps-5af36d9c:/home/mf# node mf.js 
undefined:1
{"text":"§e\n§6§lHADARIA§r
                          ^

SyntaxError: Unexpected token 
 in JSON at position 26
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (/home/mf/node_modules/mineflayer/lib/plugins/tablist.js:18:49)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/home/mf/node_modules/minecraft-protocol/src/client.js:88:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/home/mf/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/mf/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/mf/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/mf/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/mf/node_modules/protodef/src/serializer.js:82:10)```

**Comment by Nurutomo** [comment]
Try without AutoAuth

**Comment by Phaired** [comment]
Same error without auto auth, and I need it for this server

**Comment by Phaired** [comment]
https://pastebin.com/pb3Nif2F debug mode

**Comment by SiebeDW** [comment]
JSON.parse is failing to parse this json
```
{"header": "{"text":\"§e\n§6§lHADARIA§r\n§eplay.hadaria.fr§r\n§7\"}","footer": "{"text":"§b\n§b §ejoueurs en ligne§r\n§7\n§f ✦ §e§lGrades§a, §e§lclés§a, §e§lobjets §a§let bien + avec §b§l/boutique §f✦ §r\n§6"}"}
```

**Comment by Nurutomo** [comment]
Maybe the problem is `\n` unescaped

Pada tanggal Rab, 8 Jul 2020 05.34, SiebeDW <notifications@github.com>
menulis:

**Comment by Karang** [comment]
You can escape the new line using:
```js
function escapeNewline(str) {
  return str.replace(/[\n]/g, '\\n')
}
```
Then it is able to parse:
```js
JSON.parse(escapeNewline("{\"text\":\"§e\n§6§lHADARIA§r\n§eplay.hadaria.fr§r\n§7\"}"))
```

**Comment by wvffle** [comment]
Have you updated the mineflayer recently? A week ago I've fixed the same issue. I didn't see yours though. If I did, I'd inform there.

**Comment by Karang** [comment]
I don't know if he still have the issue but I connected to hadaria and had no issue with the latest mineflayer. Would be good to have confirmation from op that it is fixed.

**Comment by Phaired** [comment]
It's ok thanks everyone !
