### ISSUE TITLE
Light updates seem to have no effect

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/mineflayer#304]
Using BlockFinder plugin I wrote a simple script to find nearby unlit blocks (those that allow mob spawning) and announce the coordinates and type of the darkest one of these. However as I place torches, the bot still announces the same blocks. Something is wrong with `block.light`. Maybe spigot server isn't sending it correctly?

```
 //Install block finder
 blockFinderPlugin(bot);
 bot.findBlock({
  point: bot.entity.position,
  matching: function(block) {
    //Ignore 8 and brighter
    if(block.light>7)
      return false;
    //Ignore air
    if(block.type==0)
      return false;
    //Check if there isn't block right above it
    //If there's a block above, the torch can't be placed anyway and monsters can't spawn
    var pos = vec3(block.position);
    pos.y++;

    var obstruction=bot.blockAt(pos);
    if(obstruction!=null && obstruction.type!=0) {
      //console.log(block.position+" is obstructed by "+obstruction.displayName);
      return false;     
    }
    return true;
  },
  maxDistance: 20,
  count: 6,
}, function(err, blocks) {
  if (err) {
    bot.chat('Error trying to find unlit blocks: ' + err);
    _this.setError(1, err);
  }
  else if (blocks.length) {
    //Sort the found blocks from darkest to lightest
    blocks.sort(function(a,b){return a.light-b.light});
    bot.chat('I found an unlit '+blocks[0].displayName+' block at ' + blocks[0].position + ' - It has light of '+blocks[0].light);      
    //return;
  } else {
    bot.chat("I couldn't find any unlit blocks.");
  }
  _this.finished();
});
```

**Comment by rom1504** [comment]
Can you try to reproduce this with a vanilla server ?

**Comment by Darker** [comment]
Tried on vanilla, it's the same. Also, nobody really uses vanilla... It almost crashed my computer by it's CPU usage and has broken GUI.

![http://i.imgur.com/V6JEo2t.png][vanilla screenshot]

**Comment by Darker** [comment]
Restarting server or reloging has no effect. The light is allways 0.

**Comment by roblabla** [comment]
Vanilla is what we used to test node-mc-proto and mineflayer. That's why we always ask to reproduce on vanilla, allows us to see if it's an impl discrepency or just use doing it wrong ^^

**Comment by Darker** [comment]
Ok this is happening both in vanilla and spigot. It also seems that it's not due to block update problem but generally parsing the light value.
Is there anything I can do to hotfix that? I wanted to make a bot that carries light all over certain location.

**Comment by rom1504** [comment]
This might be related to how light is deserialized ( https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/blocks.js#L63 ), might be worth looking into.

**Comment by rom1504** [comment]
Ok so I can confirm light is broken, I added an information in chatterbox to check this (with the block command).
I believe the problem is in addColumn (https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/blocks.js#L64) or blockAt (https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/blocks.js#L143) but bitwise operations aren't really my thing. Maybe you can spot something @roblabla ?

**Comment by rom1504** [comment]
Will be fixed by #334

**Comment by rom1504** [comment]
reason why : https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L64
lights are half-bytes, not full.

Ways to fix that:
1. fix it directly
2. use prismarine-world in mineflayer

I prefer 2 since that's what we will do eventually anyway.

**Comment by rom1504** [comment]
should be fixed by #465 : needs to be checked

**Comment by falazar** [comment]
appears to still not be working in vanilla all the time, sometimes is ok. 
will check for light, add three torches, and still say it is dark. 

is there an update function I can call force recheck or ?

**Comment by rom1504** [comment]
You cannot force the server to do anything. However you can listen to the
block update event ( see the doc) and only read the light value when the
block got updated.
