### ISSUE TITLE
bot.entity.equipment is always empty array

### ISSUE THREAD

**Issue by G07cha** [PrismarineJS/mineflayer#397]
As I understand, `equipment` property should display currently equipped items(such as helmet, leggins) but it remains empty even after bot equips full set so for now here is only workaround to get equipped items is to read from 5th inventory's index where equipped armor goes.

**Comment by rom1504** [comment]
@G07cha did you eventually solve that for your plugin ? If you know how to fix it, could you make a PR ?

**Comment by rom1504** [comment]
https://github.com/G07cha/MineflayerArmorManager/blob/master/lib/invUtil.js#L47

**Comment by G07cha** [comment]
@rom1504 I thought this is dirty workaround.

**Comment by rom1504** [comment]
Yes it should be fixed.

**Comment by Frettarix** [comment]
I still see this error occurring, the bot is unable to see what it's wearing itself: bot.players[bot.username].entity.equipment[0] = undefined, with a fishing pole, but it can see what I'm wearing though. Same with bot.entity.equipment

**Comment by Karang** [comment]
> I still see this error occurring, the bot is unable to see what it's wearing itself: bot.players[bot.username].entity.equipment[0] = undefined, with a fishing pole, but it can see what I'm wearing though. Same with bot.entity.equipment

For entity.equipment[0] you can use entity.heldItem which is correctly updated. For the other pieces of equipment, this should indeed be fixed.
